### ISSUE TITLE
The Done marked tasks get undone after another addition of task.

### ISSUE THREAD

**Issue by Tilakraj0308** [Tilakraj0308/To-Do-List#1]
When a task is marked done, it shows a tick mark but as soon as the new task is added, the task returns to its original form(unmarked).
![githubimage1](https://user-images.githubusercontent.com/78500065/161434506-0665e236-6a13-4400-aa8e-103521332e3d.jpg)
Before (Marked as completed).

![githubimage2](https://user-images.githubusercontent.com/78500065/161434630-9dab8e9d-3b28-4d32-9daa-488f869336b1.jpg)
After (Again marked undone).

**Comment by sukriti-kuila** [comment]
Can I work on this issue as well?

**Comment by Tilakraj0308** [comment]
Yes you can!!
