### ISSUE TITLE
blank space can be used a title of the task

### ISSUE THREAD

**Issue by dishant-yadav** [Tilakraj0308/To-Do-List#14]

**Comment by dishant-yadav** [comment]
i would like to fix the issue

**Comment by Tilakraj0308** [comment]
> i would like to fix the issue

Can you please be a bit more descriptive?

**Comment by dishant-yadav** [comment]
I mean when i give the title as a blank space it adds the title but should return a error as  the title is blank. I have also sent the screen recording of the issue on discord.

**Comment by Tilakraj0308** [comment]
Ok you are good to go!!
