### ISSUE TITLE
Prevent addition of empty tasks.

### ISSUE THREAD

**Issue by Tilakraj0308** [Tilakraj0308/To-Do-List#2]
When the add button is clicked it always adds task even without title and description.

![githubimage3](https://user-images.githubusercontent.com/78500065/161435377-48e0c58e-6ff0-42a3-aef8-dd850b3ad6a5.jpg)

**Comment by Tilakraj0308** [comment]
> Hi @Tilakraj0308 , I would like to take the issue!

sure, you are good to go!

**Comment by sukriti-kuila** [comment]
Thanks for assigning the task. Can the output be like this? If the user tries to input a null value then one alert will be prompted as well as it won't be included in the task list. 

![image](https://user-images.githubusercontent.com/87015685/161583209-724a3953-5a75-442b-bd98-12898e2f03a9.png)

**Comment by Tilakraj0308** [comment]
yup!! That looks fine to me!!👍

**Comment by sukriti-kuila** [comment]
Okay 👍

**Comment by Tilakraj0308** [comment]
nice work!
