### ISSUE TITLE
Should not add empty task.

### ISSUE THREAD

**Issue by dishant-yadav** [Tilakraj0308/To-Do-List#5]
A feature to only add tasks with content

**Comment by dishant-yadav** [comment]
I would like to work on this feature. Is there some conventions that i need to keep in mind?

**Comment by Tilakraj0308** [comment]
Sorry, but this one's been resolved already!! The issue has been closed!!
But you can open a new issue (regarding other bugs) or propose new features as well.

**Comment by dishant-yadav** [comment]
okay
